### ISSUE TITLE
Some minor issues

### ISSUE THREAD

**Issue by zeyadkhaled** [cagdass/les-honorables#12]
1) I like the app and I use it from time to time. I was curious to see if it will figure out my departmental transfer or will it show this fall new stats. I think, from checking your crawler, that it runs over a range of values in the `?donem=` parameter. I guess as it doesn't show updated values you could perhaps add a Date check to signal the end of a semester and then update the `end` value in the crawler to include newly added semesters. And lastly, after this is figured out I don't know if you set the department based on the most recent retrieved value based on a higher `?donem=` value. I am just thinking Transfer students here.

2) I feel honored to be on top of **_Le Wall de Fame_** after working my ass off for 2 mins straight of click spamming ;)))))). Maybe, add a dictionary of IP addresses that visited a specific `Top student`.

3) Leave me in the **_Le Wall de Fame_**, pls.

**Comment by cagdass** [comment]
Hey man glad you like it. 

You'll keep your name dans Le Wall de Fame, until a student more beautiful and harnessing more fame comes. As for spamming, it is a pain in the ass, but to solve it is another kind of a pain in the ass. Most traffic I get is from Bilkent network and there IP addresses are randomly assigned to devices and I suspect multiple devices can have the same public IP address etc. I guess ideally I can combine whatever information I can get about the device, the OS, the browser, the IP address, and possibly even set a cookie on the device and have a TTL value (maybe a day, individually set for a device and retrieved student pair). This I can actually have a look into.

I can go on a rant about the transfer students. The main trouble is while you can have transfer students, you can also have people with the exact same name. They might have transferred as well, to make matters worse. Whenever I felt like doing a few extra checks to detect transfers, different people with the same name etc. I thought how I could never solve the following problem. Consider students A1 and A2, say they're both called Mehmet Yilmaz. A1 starts studying EEE in Fall 2013, has awful two semesters before transferring to ARCH where he thinks he'll thrive. And indeed he does, with his name on the high honor roll for the next six semesters. A2 starts studying CS in Fall 2013 too. He kind of likes it and and has his name on the honor roll for the first two semesters, but then a few bad things happen to him and he is no longer focused in his studies and never makes it to the roll again. So what we have is

|name|department|semester|status|
|---|---|---|---|
|mehmet yilmaz|cs|fall 2013|honor|
|mehmet yilmaz|cs|spring 2014|honor|
|mehmet yilmaz|arch|fall 2014|honor|
|mehmet yilmaz|arch|spring 2015|high honor|
|mehmet yilmaz|arch|fall 2015|high honor|
|mehmet yilmaz|arch|spring 2016|high honor|
|mehmet yilmaz|arch|fall 2016|honor|
|mehmet yilmaz|arch|spring 2017|high honor|

I know how unlikely a case such as this is to exist but since I know that I can't solve this, and a few other cases like this I historically refused to do absolutely anything about transfers and name conflicts.

**Comment by cagdass** [comment]
And as for what you said about the ?donem parameter, when I'm getting updates for a semester I go like this,

    #current = '19861'
    #end = '20171'
    current = '20172'
    end = '20173'

...

    #collectionDept.delete_many({})
    #collection.delete_many({})

If you feel like contributing, you can write a menu-like interface or plain command line arguments to choose
* whether get updates for a specific range or the entire range
* insert or upsert the rows
* delete the collection before inserting

**Comment by zeyadkhaled** [comment]
>  I guess ideally I can combine whatever information I can get about the device, the OS, the browser, the IP address, and possibly even set a cookie on the device and have a TTL value (maybe a day, individually set for a device and retrieved student pair). This I can actually have a look into.
>
Given what you said about Bilkent's mess in assigning public addresses, this sounds like the ideal approach to fix. An easier fix that is so lazy and unrealistic, just put a TTL value, say half an hour, on a student after he has been searched, and only increment his counter after TTL value expires. Because hey let's be real here who could be that sought after other than me,  _a beautiful, fame harnessing student_.

> I know how unlikely a case such as this is to exist but since I know that I can't solve this, and a few other cases like this I historically refused to do absolutely anything about transfers and name conflicts.

You, sir, convinced me.

> If you feel like contributing, you can write a menu-like interface or plain command line arguments to choose

Will look into it. 

> You'll keep your name dans Le Wall de Fame

I am forever grateful.
